phong_thuy_dict = {
    "00": "Bình an, viên mãn, khởi đầu thuận lợi.",
    "01": "Sức mạnh, khởi đầu mới, sinh khí.",
    "02": "Cân bằng, hài hòa, song hỷ.",
    "03": "Tài năng, sáng tạo, phát triển.",
    "04": "Bấp bênh, dễ thay đổi, nên cẩn trọng.",
    "05": "Trường thọ, hạnh phúc, vững bền.",
    "06": "Lộc phát, thuận lợi, có quý nhân.",
    "07": "Thất bại, xui xẻo (nên tránh chọn đầu tư lớn).",
    "08": "Phát tài, thành công, thịnh vượng.",
    "09": "Trường cửu, bền vững, phúc lộc lâu dài.",
    "10": "Trọn vẹn, tròn đầy, khởi đầu viên mãn.",
    "11": "Song hỷ, nhân đôi niềm vui, may mắn.",
    "12": "Cát lợi, thuận hòa, tình cảm bền lâu.",
    "13": "Vận hạn, cần đề phòng, tránh đầu tư liều lĩnh.",
    "14": "Kiên trì, vững chắc, vượt khó thành công.",
    "15": "Phú quý, cuộc sống đủ đầy, may mắn.",
    "16": "Phát lộc, gia đình hòa thuận.",
    "17": "Trắc trở, nhiều thử thách.",
    "18": "Phát tài, sinh lộc, phát triển mạnh mẽ.",
    "19": "Kết thúc viên mãn, trường thọ.",
    "20": "Cân bằng, đôi lứa, song hỷ.",
    "21": "Sinh khí, tươi mới, phát triển.",
    "22": "Thành công, dễ đạt mục tiêu.",
    "23": "Phát đạt, gặp nhiều may mắn.",
    "24": "Tài lộc, công danh tiến tới.",
    "25": "Hạnh phúc, may mắn, bình an.",
    "26": "Có quý nhân phù trợ.",
    "27": "Dễ mất mát, nên cẩn trọng.",
    "28": "Phát đạt, nhiều tài lộc.",
    "29": "Kết thúc tốt đẹp.",
    "30": "Duyên lành, vẹn toàn.",
    "31": "Tài lộc, công việc thăng tiến.",
    "32": "Gặp quý nhân, sự nghiệp phát triển.",
    "33": "May mắn lớn, tài lộc dồi dào.",
    "34": "Gian nan, cần kiên nhẫn.",
    "35": "Thịnh vượng, phát triển bền vững.",
    "36": "Lộc trời, có nhiều cơ hội.",
    "37": "Vận xấu, cần đề phòng tiểu nhân.",
    "38": "Phát tài, thành công.",
    "39": "Vạn sự như ý.",
    "40": "Trọn vẹn, an nhiên.",
    "41": "Ổn định, vững chắc.",
    "42": "Thuận lợi, may mắn kéo dài.",
    "43": "Vững chãi, mạnh mẽ.",
    "44": "Bấp bênh, dễ thay đổi.",
    "45": "Tài lộc nhỏ, bình yên.",
    "46": "Hạnh phúc viên mãn.",
    "47": "Cẩn trọng, không nên mạo hiểm.",
    "48": "Phát tài lớn.",
    "49": "Tiểu nhân quấy phá.",
    "50": "An lành, yên ổn.",
    "51": "Tài lộc dồi dào.",
    "52": "Thịnh vượng, nhiều điều tốt.",
    "53": "Khó khăn, cần kiên nhẫn.",
    "54": "May mắn về tình duyên.",
    "55": "Song phúc, tài lộc nhân đôi.",
    "56": "Phát triển, mở rộng.",
    "57": "Dễ bị thị phi.",
    "58": "Thành công rực rỡ.",
    "59": "Bế tắc, cần tìm lối đi mới.",
    "60": "An nhàn, tự do.",
    "61": "Vạn sự hanh thông.",
    "62": "Công việc thuận lợi.",
    "63": "Phát triển tài lộc.",
    "64": "Vững bền, trường tồn.",
    "65": "Cơ hội lớn, dễ phát triển.",
    "66": "Song lộc, phát tài.",
    "67": "Cẩn trọng thị phi.",
    "68": "Lộc trời ban.",
    "69": "Tình cảm viên mãn.",
    "70": "Sự nghiệp ổn định.",
    "71": "Khó khăn tạm thời.",
    "72": "Hưởng lộc trời.",
    "73": "Dễ gặp thử thách.",
    "74": "Phát triển lâu dài.",
    "75": "An lành, may mắn.",
    "76": "Sự nghiệp lên cao.",
    "77": "Song thất, nên tránh.",
    "78": "Phát đạt bất ngờ.",
    "79": "Phát triển mạnh mẽ.",
    "80": "Thành công viên mãn.",
    "81": "Phúc lộc trọn đời.",
    "82": "May mắn về tiền bạc.",
    "83": "Gặp quý nhân giúp đỡ.",
    "84": "Công danh rộng mở.",
    "85": "Hòa thuận, ổn định.",
    "86": "Phát lộc lớn.",
    "87": "Dễ bị cản trở.",
    "88": "Phát tài phát lộc.",
    "89": "Viên mãn, trường thọ.",
    "90": "Khởi đầu mới, tươi sáng.",
    "91": "Thành công ngoài mong đợi.",
    "92": "Hạnh phúc viên mãn.",
    "93": "Ổn định, phát triển lâu dài.",
    "94": "Dễ gặp may bất ngờ.",
    "95": "Làm ăn phát đạt.",
    "96": "Phúc lộc dồi dào.",
    "97": "Dễ vấp váp, nên bình tĩnh.",
    "98": "Vạn sự như ý.",
    "99": "Song cửu: Đại cát, trường thọ, phú quý.",
}
